testwe_api_public :
    type: rest
    resource: "Attentra\\ApiBundle\\Controller\\PublicRestController"
    name_prefix:  attentra_api_public_
    prefix: "/public"

testwe_api_user :
    type: rest
    resource: "Attentra\\ApiBundle\\Controller\\ResourceRestController"
    name_prefix:  attentra_api_resource_
#    prefix: "/resource"
