testwe_api_public :
    type: rest
    resource: "Attentra\\ApiBundle\\Controller\\PublicController"
    name_prefix:  attentra_api_public_
    prefix: "/public"

testwe_api_resource :
    type: rest
    resource: attentra_api.resource.controller #"Attentra\\ApiBundle\\Controller\\ResourceController"
    name_prefix:  attentra_api_

testwe_api_resourcegroup :
    type: rest
    resource: attentra_api.resourcegroup.controller
    name_prefix:  attentra_api_

testwe_api_timeinput :
    type: rest
    resource: attentra_api.timeinput.controller
    name_prefix:  attentra_api_
