testwe_api_public :
    type: rest
    resource: "Attentra\\ApiBundle\\Controller\\PublicController"
    name_prefix:  attentra_api_public_
    prefix: "/public"

testwe_api_user :
    type: rest
    resource: attentra_api.resource.controller #"Attentra\\ApiBundle\\Controller\\ResourceController"
    name_prefix:  attentra_api_
