parameters:
    attentra_api.resource.class: Attentra\ResourceBundle\Entity\Resource
    attentra_api.resource.handler.class: Attentra\ApiBundle\Handler\ResourceHandler
    attentra_api.resource.form.type.class: Attentra\ResourceBundle\Form\ResourceType

services:
    attentra_api.resource.handler:
        class: %attentra_api.resource.handler.class%
        arguments: [@doctrine.orm.entity_manager, %attentra_api.resource.class%, @form.factory, %attentra_api.resource.form.type.class%]

    attentra_api.resource.controller:
        class: Attentra\ApiBundle\Controller\ResourceController
        arguments: [@service_container, @attentra_api.resource.handler]
