
attentra_web:
    resource: @AttentraWebBundle/Resources/config/routing.yml

attentra_resource:
    resource: @AttentraResourceBundle/Resources/config/routing.yml

attentra_time:
    resource: @AttentraTimeBundle/Resources/config/routing.yml

attentra_api:
    type: rest
    resource: @AttentraApiBundle/Resources/config/routing.yml
    prefix: "/api"
    options: { i18n: false }
